import Foundation

struct ClipboardHistoryPasteboardMetadata: Equatable, Sendable {
    let generation: Int
    let advertisedTypeIdentifiers: Set<String>
    let declaredSourceBundleIdentifier: String?

    init(
        generation: Int,
        advertisedTypeIdentifiers: Set<String>,
        declaredSourceBundleIdentifier: String? = nil
    ) {
        self.generation = generation
        self.advertisedTypeIdentifiers = advertisedTypeIdentifiers
        self.declaredSourceBundleIdentifier = declaredSourceBundleIdentifier
    }
}

struct ClipboardHistoryObservationPolicy {
    static let universalClipboardTypeIdentifier =
        "com.apple.is-remote-clipboard"

    static let exclusionTypeIdentifiers: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "net.antelle.keeweb",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
    ]

    enum Decision: Equatable, Sendable {
        case exclude
        case capture(ClipboardHistoryCaptureSource)
    }

    func evaluate(
        _ metadata: ClipboardHistoryPasteboardMetadata,
        copyEventSource: ClipboardHistoryApplicationSource?,
        observationSource: ClipboardHistoryApplicationSource?,
        configuration: ClipboardHistoryMonitoringConfiguration
    ) -> Decision {
        guard metadata.advertisedTypeIdentifiers.isDisjoint(
            with: Self.exclusionTypeIdentifiers
        ) else {
            return .exclude
        }

        if metadata.advertisedTypeIdentifiers.contains(
            Self.universalClipboardTypeIdentifier
        ) {
            return configuration.ignoresUniversalClipboard
                ? .exclude
                : .capture(.universalClipboard)
        }

        let source: ClipboardHistoryCaptureSource
        if let declared = nonEmpty(metadata.declaredSourceBundleIdentifier) {
            source = ClipboardHistoryCaptureSource(
                bundleIdentifier: declared,
                displayName: nil,
                provenance: .declared
            )
        } else if let copyEventSource {
            source = ClipboardHistoryCaptureSource(
                bundleIdentifier: copyEventSource.bundleIdentifier,
                displayName: copyEventSource.displayName,
                provenance: .copyEvent
            )
        } else if let observationSource {
            source = ClipboardHistoryCaptureSource(
                bundleIdentifier: observationSource.bundleIdentifier,
                displayName: observationSource.displayName,
                provenance: .observation
            )
        } else {
            source = .unknown
        }

        if let bundleIdentifier = source.bundleIdentifier,
            configuration.excludedBundleIdentifiers.contains(bundleIdentifier)
        {
            return .exclude
        }
        return .capture(source)
    }

    private func nonEmpty(_ value: String?) -> String? {
        guard let trimmed = value?.trimmingCharacters(
            in: .whitespacesAndNewlines
        ), !trimmed.isEmpty else {
            return nil
        }
        return trimmed
    }
}
